#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can webtoptribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-webtop5-update event
#--------------------------------------------------

my $event = "nethserver-webtop5-update";

event_actions($event, 
                     'initialize-default-databases' => '00',
                     'nethserver-webtop5-conf' => '20',
                     'nethserver-webtop5-conf-db' => '30',
                     'nethserver-webtop5-locale-tz' => '40',
                     'nethserver-webtop5-clean-logs' => '50'
);
event_templates($event, 
                     '/etc/dovecot/dovecot.conf',
                     '/etc/httpd/conf.d/webtop.conf',
                     '/etc/httpd/conf.d/default-virtualhost.inc',
		     '/etc/webtop/webtop.properties',
                     '/etc/webtop/webtop/data-sources.xml',
                     '/usr/share/webtop/z-push/config.json',
                     '/usr/share/webtop/webdav/config.json',
                     '/etc/sysconfig/tomcat8@webtop'
);
event_services($event, 
                     'tomcat8@webtop' => 'restart',
                     'dovecot' => 'restart',
                     'httpd' => 'reload',
                     'rh-php72-php-fpm' => 'restart',
);


#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

$event = 'pre-backup-data';

event_actions($event, 'nethserver-webtop5-backup' => 50);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

$event = 'post-restore-data';

event_actions($event, 'nethserver-webtop5-restore' => 50);

event_services($event, 'tomcat8@webtop' => 'restart');


#--------------------------------------------------
# actions for nethserver-mail-server-save event
#--------------------------------------------------

$event = 'nethserver-mail-server-save';

event_actions($event, 'nethserver-webtop5-conf-db' => 50);

event_services($event, 'tomcat8@webtop' => 'restart');

#--------------------------------------------------
# actions for nethserver-sssd-save event
#--------------------------------------------------

$event = 'nethserver-sssd-save';

event_actions($event, 'nethserver-webtop5-conf-db' => 50);

event_services($event, 'tomcat8@webtop' => 'restart');
