#!/bin/bash

su - postgres -c "psql -lqt | cut -d \| -f 1 | grep -q -w webtop5"
if [ $? -eq 1 ]; then # database do not exists

    # create db and users
    tmp_sql=`mktemp`
    chmod a+r $tmp_sql
    password=`perl -e "use NethServer::Password; print NethServer::Password::store('webtop5');"`
cat << EOF > $tmp_sql
CREATE database webtop5;
CREATE USER sonicle WITH PASSWORD '$password';
ALTER USER sonicle WITH SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE webtop5 to sonicle;
EOF
    su - postgres  -c "psql < $tmp_sql" >/dev/null
    rm -f $tmp_sql

    # initialize db schema
    for sql in `find /usr/share/webtop/sql/schema/ -name \*.sql`
    do
        echo "Loading: $sql ..."
        su - postgres  -c "psql webtop5 < $sql" >/dev/null
    done

    # initialize db data
    for dsql in `find /usr/share/webtop/sql/data/ -name \*.sql`
    do
        echo "Loading: $dsql ..."
        su - postgres  -c "psql webtop5 < $dsql" >/dev/null
    done


    # fix table owner
    tmp_sql=`mktemp`
    chmod a+r $tmp_sql
    for tbl in `su - postgres  -c "psql -qAt -c \"select tablename from pg_tables where schemaname = 'public';\" webtop5"` \
               `su - postgres  -c "psql -qAt -c \"select sequence_name from information_schema.sequences where sequence_schema = 'public';\" webtop5"` \
               `su - postgres  -c "psql -qAt -c \"select table_name from information_schema.views where table_schema = 'public';\" webtop5"` ;
    do
        echo "alter table \"$tbl\" owner to sonicle;" >> $tmp_sql
    done
    su - postgres  -c "psql webtop5 < $tmp_sql" >/dev/null
    rm -f $tmp_sql
else
    for sql in `find /usr/share/webtop/updates/pre -name \*.sql`
    do
        su - postgres -c "psql webtop5 < $sql" >/dev/null
    done
fi

