#!/usr/bin/perl

use esmith::ConfigDB;
use File::Temp;
use NethServer::SSSD;
use JSON;
my $sssd = new NethServer::SSSD();

my $db = esmith::ConfigDB->open_ro() or die "Could not open config db";

$fh = File::Temp->new();
my ($login,$pass,$uid,$gid) = getpwnam('postgres') or die "postgres not in passwd file";
chown $uid, $gid, $fh->filename;
print $fh "DELETE FROM core.domains WHERE domain_id = 'NethServer';\n";

my $encoded = '';
my $secret=$sssd->bindPassword();

# Some obsucre perl magic, thanks to Davidep
pipe RH, WH;
open(OLDIN, "<&STDIN");
open(STDIN, "<&RH");
if(open(PIPE, "-|")) {
    close(RH);
    print WH $secret;
    close(WH);
    $encoded = <PIPE>;
    chomp($encoded);
} else {
    exec("java -classpath /usr/share/webtop/ WebtopPassEncode");
}
close(PIPE);
close(RH);
open(STDIN, "<&OLDIN");

my $domain = $db->get('DomainName')->prop('type');
my $user = $sssd->bindDN();
my $uri = $sssd->ldapURI();
my $port = "389";
my $ssl = "null";
my $dir_params;
my $prefix = '';

if ( $uri =~ /^ldaps/ ) {
    $ssl = "'SSL'";
    $port = "636";
}
if ( $sssd->startTls() ) {
    $ssl = "'STARTTLS'";
}

if ($sssd->isAD()) {
    $prefix = 'ad://';
    $dir_params =  {
        loginDn => $sssd->userDN(),
        loginFilter => undef,
        userIdField => 'sAMAccountName',
        userDn => $sssd->userDN(),
        userFilter => undef,
        userFirstnameField => 'givenName',
        userLastnameField => 'sn',
        userDisplayNameField => 'displayName'
    };
} else {
    $prefix = 'ldap://';
    $dir_params =  {  
        loginDn => $sssd->userDN(),
        loginFilter => undef,
        userIdField => 'uid',
        userDn => $sssd->userDN(),
        userFilter => undef,
        userFirstnameField => 'givenName',
        userLastnameField => 'sn',
        userDisplayNameField => 'gecos'
    };
}

$uri = $prefix . $sssd->host() . ":" . $port;

my $query = "INSERT INTO \"core\".\"domains\" (\"domain_id\", \"internet_name\", \"enabled\", \"description\", \"user_auto_creation\", \"dir_uri\", \"dir_admin\", \"dir_password\", \"dir_connection_security\", \"dir_case_sensitive\", \"dir_password_policy\", \"dir_parameters\") VALUES ('NethServer', '$domain', 't', 'NethServer', 't', '$uri', '$user', '$encoded', $ssl, 'f', 'f', '". encode_json($dir_params)."');\n";

print $fh $query;

# Set also public url
my $public_url = $db->get_prop('webtop','PublicUrl') || 'http://'.$db->get('SystemName')->prop('type').'.'.$domain.'/webtop';

print $fh "DELETE FROM \"core\".\"settings\" WHERE service_id = 'com.sonicle.webtop.core' and key = 'public.url';\n";
print $fh "INSERT INTO \"core\".\"settings\" (\"service_id\", \"key\", \"value\") VALUES ('com.sonicle.webtop.core', 'public.url', '$public_url');\n";

system("su - postgres  -c 'psql webtop5 < ".$fh->filename."' >/dev/null");
