#!/bin/bash

PASS=$1

if [ -z "$PASS" ]; then
    echo "Usage: $0 <new_password>"
    exit 1
fi
tmp_sql=`mktemp`
chmod a+r $tmp_sql
password=`perl -e "use NethServer::Password; print NethServer::Password::store('webtop5');"`

cat << EOF > $tmp_sql
UPDATE "core"."local_vault" SET "password_type"='PLAIN', "password"='$PASS' WHERE ("domain_id"='*') AND ("user_id"='admin');
EOF
su - postgres  -c "psql webtop5 < $tmp_sql" >/dev/null
rm -f $tmp_sql
