#!/bin/bash

#
# Download and deploy a staging WAR
#

VERSION=$1
WORK_DIR=/tmp/webtop-staging-$VERSION
LOG="$WORK_DIR/deploy.log"
BASE_URL="https://www.sonicle.com/nethesis/webtop5/staging/"
STAGING_FILE=$WORK_DIR/wt-staging-$1.war
STAGING_URL="https://www.sonicle.com/nethesis/webtop5/staging/webtop5%23%23$1.war"
BACKUP_DIR="$WORK_DIR/webtop-"$(date +%s)

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <WAR-version>"
    echo
    echo "Example:"
    echo "   staging-deploy 0265"
    echo
    echo "Check this site for available versions: $BASE_URL"
    exit
fi

# Create working directory
mkdir -p $WORK_DIR

# Redirect stderr and stdout also to logfile
exec > >(tee -ia $LOG)
exec 2> >(tee -ia $LOG)

which unzip &>/dev/null
# Install required dependcies
if [ $? -gt 0 ]; then
    yum install unzip -y
fi

if [ $? -gt 0 ]; then
    echo "Can't install unzip"
    exit 1
fi

echo "$(date +'%h %d %H:%M:%S') Starting deploy"

echo "Downloading staging war"
#wget "$STAGING_URL" -O $STAGING_FILE
true
if [ $? -gt 0 ]; then
    echo "Can't download staging file: $STAGING_URL"
    exit 1
fi

if [ -z $STAGING_FILE ]; then
    echo "Downloaded file is invalid"
    exit 1:
fi

echo "Stopping tomcat"
systemctl stop tomcat8@webtop

echo "Creating backup dir: "
mv /var/lib/tomcats/webtop/webapps/webtop/ $BACKUP_DIR

echo "Extracting war file"
unzip -d /var/lib/tomcats/webtop/webapps/webtop/ $STAGING_FILE

echo "Restarting tomcat"
/sbin/e-smith/signal-event nethserver-webtop5-update

echo
echo "Use 'journalctl -u tomcat8@webtop' to inspect webapp startup"
echo "The restul log can be found at $LOG"
echo "At the end, you can remove the temporary directory: $WORK_DIR"
echo

echo "$(date +'%h %d %H:%M:%S') Deploy of staging WAR#$1 done!"
